#pragma once
#include <functional>
#include <list>
#include <string>
#include <unordered_map>
#include <manifold/manifold.h>

namespace chisel::csg {

// ---------------------------------------------------------------------------
// MeshCache — a simple fixed-capacity LRU cache mapping a string key to a
// Manifold.  Keys are generated by MeshEvaluator based on node parameters
// and the accumulated transform, so unchanged subtrees reuse prior results.
// ---------------------------------------------------------------------------
class MeshCache {
public:
    explicit MeshCache(std::size_t maxEntries = 128);

    // Return the cached Manifold for key, or call compute() and cache it.
    manifold::Manifold getOrCompute(const std::string& key,
                                    std::function<manifold::Manifold()> compute);

    void clear();
    std::size_t size() const { return m_map.size(); }

private:
    struct Entry {
        manifold::Manifold mesh;
    };

    using LruList   = std::list<std::string>;          // MRU front, LRU back
    using LruIter   = LruList::iterator;
    using MapEntry  = std::pair<Entry, LruIter>;

    std::size_t                              m_maxEntries;
    LruList                                  m_lru;
    std::unordered_map<std::string, MapEntry> m_map;

    void evictLru();
    void touch(const std::string& key, LruIter it);
};

} // namespace chisel::csg
